[package]
name = "datawhirr"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-native-tls"] }
